create extension if not exists pg_trgm;

create table if not exists vehicles (
    id bigint generated by default as identity primary key,
    kbb_id text unique not null, 

    -- Core vehicle information
    year int, 
    make text, 
    model text,
    category text,

    -- Pricing 
    starting_price numeric,

    -- Fuel economy
    fuel_economy text,

    -- Ratings
    expert_rating numeric(3, 1),
    consumer_rating numeric(3, 1),

    -- Description
    description text,

    -- Metadata
    created_at timestamp with time zone default timezone('utc'::text, now()),
    updated_at timestamp with time zone default timezone('utc'::text, now()),

    -- 3. Generated Column for Full Text Search
    -- This automatically concatenates Year + Make + Model for fast searching
    search_vector tsvector generated always as (
        to_tsvector('english', coalesce(year::text, '') || ' ' || coalesce(make, '') || ' ' || coalesce(model, '')) 
    ) stored
);

-- 4. Indexes for Full Text Search
create index idx_v