-- 1. Enable the Fuzzy Matching Extension (Critical for Facebook Titles)
create extension if not exists pg_trgm;

-- 2. Create the Table
create table if not exists vehicles (
    id bigint generated by default as identity primary key,
    kbb_id text unique not null, 

    -- Core Vehicle Details
    name text,             
    year int,              
    make text,             
    model text,            
    category text,         

    -- Pricing & Fuel Economy
    -- RENAMED: matches Python 'price_reference' and your Index
    price_reference numeric, 
    
    -- RENAMED: matches Python 'mpg_combined'
    mpg_combined int,

    -- Ratings
    -- RENAMED: matches Python 'rating_expert'
    rating_expert numeric(3, 1),
    rating_consumer numeric(3, 1),

    -- Description
    description text,

    -- Metadata
    created_at timestamp with time zone default timezone('utc'::text, now()),
    updated_at timestamp with time zone default timezone('utc'::text, now()),

    -- 3. Generated Column for Full Text Search (Optional but good for UI)
    search_vector tsvector generated always as (
        to_tsvector('english', 
            coalesce(year::text, '') || ' ' || 
            coalesce(make, '') || ' ' || 
            coalesce(model, '') || ' ' || 
            coalesce(name, '')
        )
    ) stored
);

-- 4. Trigram Index for "Smart Matching" (The Secret Sauce)
-- We index the concatenation of Year + Make + Model.
-- This allows finding "2017 Toyta Camry" against "2017 Toyota Camry"
create index idx_vehicles_fuzzy_match 
on vehicles 
using gin ((year::text || ' ' || make || ' ' || model) gin_trgm_ops);

-- 5. Standard Indexes for Speed
create index idx_vehicles_search on vehicles using gin(search_vector);
create index idx_vehicles_price on vehicles(price_reference);
create index idx_vehicles_make on vehicles(make);

-- 6. Auto-update 'updated_at' timestamp
create or replace function update_modified_column()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language 'plpgsql';

create trigger update_vehicles_modtime
    before update on vehicles
    for each row
    execute procedure update_modified_column();